### PR TITLE
fix: emojis appear differently on different platforms

### LINKED ISSUE #62: Emojis not consistent across platforms
Emojis are working well on Linux, however other platforms have issues:

- Android has some emojis missing, likely because the system emoji font is out of date.
- Windows displays emojis in the native style, and is missing many emojis:

ff1

### PR DESCRIPTION
**Pull request by Merrit**
Include the Noto Color Emoji font in the package and use it to render
emojis on all platforms. This ensures that emojis appear the same on
all platforms, even if the user's system does not have the Noto Color
Emoji font installed.

Resolves #62

### CODE REVIEW

**Comment by Merrit** [comment]
The idea was to have the `google_fonts` package pull in the `Noto Color Emoji` font, thereby ensuring that the same set of high-quality and up to date emojis would be available on all platforms.

On Linux everything was already working well, and this change had no real effect aside from ensuring that distros without the emoji font or with an old version wouldn't have issues.

On Android this seems to have resolved the issue with missing emojis.

On Windows however, this causes the emojis to be invisible and I can't really figure out why so far.

ff2

**Comment by TheGB0077** [comment]
Maybe a platform check if it's Windows to then load specifically the Sugoe UI Emoji font would be an ideal solution, that's the only one I got by default on my Windows 10 install.

image

Edit: It looks like that this font is exactly the problem and I just realized that 😖

**Comment by TheGB0077** [comment]
Maybe including the fonts with the App could fix it, instead of fetching them from Google.

**Comment by Merrit** [comment]
> Maybe including the fonts with the App could fix it, instead of fetching them from Google.

That's a good idea, oddly though when including the font file manually it still shows the native Windows emojis instead of the Noto ones.

¯\\\_(ツ)_/¯

**Pull request merged**
